services:
  core-connector:
    image: mojaloop/mtn-ug-core-connector:v1.22.0.local # edit this line to set image name
    env_file: ./core-connector.env 
    ports:
      - "13003:3003"
      - "13004:3004"

  dfsp-api:
    image: stoplight/prism:4
    command: 'mock -h 0.0.0.0 /tmp/api.oas3.yml'
    volumes:
      - ./api.oas3.yml:/tmp/api.oas3.yml:ro
    ports:
      # Serve the mocked API locally as available on port 8080
      - '18080:4010'