services:
  core-connector:
    image: mojaloop/mtn-ug-core-connector:v1.25.0 # edit this line to set image name
    env_file: ./core-connector.env 
    ports:
      - "13003:3003"
      - "13004:3004"
